version: '3.2'
services:
  server1:
    build: 
      context: .
      dockerfile: Server1-Dockerfile
    environment:
      dockerName: "Server#1"
    ports:
      - "8080:8080" 
      - "443:8443"
      - "4200:4200"
      - "4201:4201"
      - "4203:4203"
      - "4204:4204"
      - "4212:4212"
    networks:
      testing_net:
        ipv4_address: 172.28.1.1
  server2:
    build: 
      context: .
      dockerfile: Server2-Dockerfile
    environment:
      dockerName: "Server#2"
    ports:
      - "8081:8080" 
      - "444:8443"
      - "4300:4200"
      - "4301:4201"
      - "4303:4203"
      - "4304:4204"
      - "4312:4212"
    networks:
      testing_net:
        ipv4_address: 172.28.1.2
  server3:
    build: 
      context: .
      dockerfile: Server3-Dockerfile
    environment:
      dockerName: "Server#3"
    ports:
      - "8082:8080" 
      - "445:8443"
      - "4400:4200"
      - "4401:4201"
      - "4403:4203"
      - "4404:4204"
      - "4412:4212"
    networks:
      testing_net:
        ipv4_address: 172.28.1.3
networks:
  testing_net:
    # driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16